// <auto-generated />
namespace Lynda_MVC_ATM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtranstration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtranstration));
        
        string IMigrationMetadata.Id
        {
            get { return "201706270251005_add-transtration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
